### ISSUE TITLE
No module named example_site.settings

### ISSUE THREAD

**Issue by VickiShaw94** [duosecurity/duo_python#27]
Upon following the steps after python REPL, setting up django throws an import error:

```
>>> import os
>>> os.environ.setdefault("DJANGO_SETTINGS_MODULE", "example_site.settings")
'example_site.settings'
>>> import django
>>> django.setup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vicki/duo_python/.env/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/vicki/duo_python/.env/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/Users/vicki/duo_python/.env/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/vicki/duo_python/.env/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named example_site.settings
>>>
```

**Comment by VickiShaw94** [comment]
You need to be in the duo_python/demos/django directory
